-- Exercises 1–3 in Section 2, Chapter 10 on page 339
-- 1. Use MySQL Workbench to create an EER diagram for a database that stores
-- information about prodt1cts.
-- Each product must have a product name, description, and price.
-- Each product must belong to one category.
-- Each category must have a category name and description.
-- Each category can include multiple products.

-- 2. Use MySQL Workbench to create an EER diagram for a database that stores
-- infor1nation about customers.
-- Each customer must have an email address, first name, and last name.
-- Each customer can have two or more addresses.
-- Each customer can have a default billing address and a default shipping
-- address.
-- Each address must have a street address, city, state, postal code, and
-- country.
-- Each country name should be stored in one place only. In other words, you
-- shouldn't store the name of the country, which may be many characters, in
-- the address.

-- 3. Use MySQL Workbench to create an EER diagram for a database that tracks
-- the memberships for an association and for the groups within the association.
-- Each member must have an email address, fit·st name, and last name.
-- Each member can belong to any number of groups.
-- Each group must have a name.
-- Each group can have any number of members.